[tool:pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
testpaths =
    tests
addopts = --tb=short -v --cov=shop --cov=user --cov-report=term-missing --cov-report=html
django_find_project = false