# Generated by Django 5.2.10 on 2026-01-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0006_alter_order_options_remove_order_comment_and_more'),  # ← укажи имя ПОСЛЕДНЕЙ миграции
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(
                max_length=20,
                choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')],
                default='delivery',
                verbose_name='Тип доставки'
            ),
        ),
    ]